### ISSUE TITLE
Memory Leak (Display/PIL) in development branch

### ISSUE THREAD

**Issue by Gunsmithy** [sensorian/SensorianHubClient#14]
An exception raised in the program while I was coding alerted me to a new memory leak after the solved DisplayValues one. It was likely introduced by the implementation of a Flask server on its own thread/process. Might have to take a look at subprocess use for Public IP updating as well. Below is the exception that was raised.

`Exception in thread PublicIPThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "Sensorian_Client.py", line 345, in run
    methods[self.method]()
  File "Sensorian_Client.py", line 554, in UpdatePublicIP
    proc = subprocess.Popen(["curl", "-s", "-4", "icanhazip.com"], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory`

**Comment by Gunsmithy** [comment]
Nope, it's a resurgence of the display bug. PIL might be in use again. Setting Display Enabled to False in the config keeps the memory usage rock solid. It should also be noted that it drops CPU usage on my Pi 1 B+ from about 40% to about 1%. Should investigate the leak/installed imaging modules first, including the install script, but also look into optimizing the display performance if possible.

**Comment by Gunsmithy** [comment]
Purging PIL and installing the latest Pillow, 3.2.0 fixes the memory leak but makes the display look all wonky. There is a different text offset or something. Going to see what happens with Pillow 2.6.1 as I've previously used.

**Comment by Gunsmithy** [comment]
Purging PIL and installing the latest Pillow, 3.2.0 fixes the memory leak, sitting at a stable 20980 RES according to top, but makes the display look all wonky. There is a different text offset or something. Going to see what happens with Pillow 2.6.1 as I've previously used.

**Comment by Gunsmithy** [comment]
Purging PIL and installing the latest Pillow, 3.2.0 fixes the memory leak, sitting at a stable 20980 RES according to top, but makes the display look all wonky. There is a different text offset or something. Going to see what happens with Pillow 2.6.1 as I've previously used.

**Comment by Gunsmithy** [comment]
Pillow 2.6.1 reverted the display to its original look, but also the memory leak. 3.2.0 seems to be the one to use. Stable at 20996 RES this time. I will have to adjust the display method to see if I can get it looking normal again. The CPU usage remains in the 30's to 40% so that's still something to be possibly improved too.

**Comment by Gunsmithy** [comment]
After a reboot, 21408 seems to be another amount of memory it also likes to sit around. Also stable though.
